#!/bin/bash

set -eu

DIR=$(cd "${BASH_SOURCE[0]%/*}" && pwd)
SCRIPT="$DIR/${BASH_SOURCE[0]##*/}"

source "$1"

vizor razor node prepare  \
    -m 26:2d:15:00:0c:b8  \
    -r test               \
    -t windows            \
    -k razor_policy            -v "$razor_policy"             \
    -k image                   -v "$image"                    \
    -k hostname                -v "$hostname"                 \
    -k description             -v "$description"              \
    -k product_key             -v "$product_key"              \
    -k owner                   -v "$owner"                    \
    -k organization            -v "$organization"             \
    -k ui_language             -v "$ui_language"              \
    -k input_locale            -v "$input_locale"             \
    -k user_locale             -v "$user_locale"              \
    -k system_locale           -v "$system_locale"            \
    -k manufacturer            -v "$manufacturer"             \
    -k model                   -v "$model"                    \
    -k support_hours           -v "$support_hours"            \
    -k support_phone           -v "$support_phone"            \
    -k support_url             -v "$support_url"              \
    -k timezone                -v "$timezone"                 \
    -k administrative_user     -v "$administrative_user"      \
    -k administrative_password -v "$administrative_password"  \
    -k regular_user            -v "$regular_user"             \
    -k regular_password        -v "$regular_password"         \
    -k horizontal_resolution   -v "$horizontal_resolution"    \
    -k vertical_resolution     -v "$vertical_resolution"      \
    -k colour_depth            -v "$colour_depth"             \
    -k dpi                     -v "$dpi"                      \
    -k refresh_rate            -v "$refresh_rate"             \
    -k first_run_command_1     -v "$first_run_command_1"      \
    -k first_run_command_2     -v "$first_run_command_2"      \
    -k first_run_command_3     -v "$first_run_command_3"      \
    
