#!/bin/bash

# Installing wimlib

FORCE="$FORCE"
set -eu

src_url="${1:-https://git.ipxe.org/releases/wimboot/wimboot-latest.tar.bz2}"
filename="${src_url##*/}"
dirname="${filename%.tar.*}"

dirs=( wimboot-*/ )                                                                                                               
latest=$( printf "%s\n" "${dirs[@]}" | sort -t . -k 1,1n -k 2,2n -k 3,3n -k 4,4n )

if [[ -e "$latest"/wimboot ]]; then
  echo -e "wimboot ($latest/wimboot) already unpacked.\n"
  [[ $FORCE ]] || exit 0
fi

wget "$src_url" -O "$filename"

tar xf "$filename"

dirs=( wimboot-*/ )                                                                                                               
latest=$( printf "%s\n" "${dirs[@]}" | sort -t . -k 1,1n -k 2,2n -k 3,3n -k 4,4n )

( if cd "$latest"; then
    rm -f wimboot
    ( cd src && make clean && make )
    ln -vf wimboot ../
  fi
)

