#!/bin/bash


echo "Downloading KB3AIK_EN.iso ... "

src_url="${1:-http://download.microsoft.com/download/8/E/9/8E9BBC64-E6F8-457C-9B8D-F6C9A16E6D6A/KB3AIK_EN.iso}"
filename="${src_url##*/}"

if [[ -e $filename ]]; then
  echo -e "KB3AIK_EN.iso already downloaded.\n"
  exit 0;
fi
wget -c "$src_url" -O "$filename"

