#!/bin/bash

set -eu

pkgs_to_install=()

for pkg in \
    postgresql postgresql-client \
 ; do
  if ! dpkg -s "$pkg" &> /dev/null; then
    pkgs_to_install+=( "$pkg" )
  fi
done

if (( ${#pkgs_to_install[@]} > 0 )); then
  sudo aptitude install -y --without-recommends "${pkgs_to_install[@]}"
fi

# sudo -u postgres createuser -P -SDR razor
sudo -u postgres psql template1 <<<"CREATE USER razor WITH PASSWORD '***REMOVED***';"
sudo -u postgres psql template1 <<<"CREATE DATABASE razor;"

# sudo -u postgres psql template1 <<<"CREATE DATABASE razor_dev;"
# sudo -u postgres psql template1 <<<"GRANT ALL PRIVILEGES ON DATABASE razor_dev TO razor;"
sudo -u postgres createdb -O razor razor_dev

# sudo -u postgres psql template1 <<<"CREATE DATABASE razor_test;"
# sudo -u postgres psql template1 <<<"GRANT ALL PRIVILEGES ON DATABASE razor_test TO razor;"
sudo -u postgres createdb -O razor razor_test

# sudo -u postgres psql template1 <<<"CREATE DATABASE razor_prd;"
# sudo -u postgres psql template1 <<<"GRANT ALL PRIVILEGES ON DATABASE razor_prd TO razor;"
sudo -u postgres createdb -O razor razor_prd

