#!/bin/bash

VAZOR_LIB_DIR='/var/www'

ISO_CACHE_DIR="$VIZOR_LIB_DIR/iso"
ISO_IMAGE_DIR="$VIZOR_LIB_DIR/img"

ISO_LIST_DIR="$ISO_CACHE_DIR/lists"
ISO_META_DIR="$ISO_CACHE_DIR/meta"

TFTPD_ROOT_DIR="$VIZOR_LIB_DIR/pxe"
PXELINUX_CFG="$TFTPD_ROOT_DIR/pxelinux.cfg"

RAZOR_REPO_ROOT_DIR="$ISO_IMAGE_DIR"

