#!/bin/bash

set -xv
TIMEZONE='GMT Standard Time'
PXE_HOST="$(hostname -f)"   # Host delivering PXE/HTTP, etc
RAZOR_HOST="$(hostname -f)"

TIMEZONE="${TZ:-$(</etc/timezone)}"
KEYMAP="$XKBLAYOUT"
ROOT_PASSWD='***REMOVED***'

