#!/bin/bash

# SYNOPSIS
#  Destroy a virtual machine.

source defaults.sh
source utils.sh

declare vm_id= vm_name=

while getopts ":hi:n:" opt; do
  case $opt in
    i) vm_id="$OPTARG"
      ;;
    n) vm_name="$OPTARG"
      ;;
    h) show_help; exit 3;
      ;;
    *) die "Unrecognized/Unimplemented option '$opt'"
      ;;
  esac
done

[[ -z $vm_id && -z $vm_name ]] && die "Neither VM name (-n) nor VM id (-i) not specified."

if [[ $vm_name ]]; then
  vm=$(cloudmonkey list virtualmachines keyword="$vm_name" filter=name,id)
  vm_count=$( jq -c -r '.count' <<<"$vm" )

  if [[ -z $vm_count ]] ; then
    die "No virtualmachine found for '$vm_name'"
  elif (( vm_count > 1 )); then
    names=( $(jq -c -r '.virtualmachine[]'  <<<"$vm") )
    printf -v vm_list "  %s\n" "${names[@]}"
    die "Multiple ($vm_count) candidates found, unable to disambiguate from\n$vm_list"
  else
    vm_id=$( jq -e -c -r '.virtualmachine[].id'   <<<"$vm" )
    vm_name=$( jq -e -c -r '.virtualmachine[].name' <<<"$vm" )
  fi
fi

[[ -z $vm_id ]] && die "No virtualmachine ID resolved."

log "Destroying virtualmachine '$vm_id' ($vm_name)"
cloudmonkey detach iso virtualmachineid="$vm_id" &>/dev/null || true
ret=$( cloudmonkey destroy virtualmachine id="$vm_id" )

if grep -iq '^Error' <<<"$ret"; then
  args="$@"
  printf -v errstr "%s\n  %s\n  %s" "$0" "$ret" "$args"
  die "$errstr"
else
  # TODO. CM seems to add progress bar info on STDOUT
  sed -r -e '1d' <<<"$ret" | jq -S -e '.'
fi

