#!/bin/bash

# SYNOPSIS
#   VM Instance actions

source defaults.sh
source utils.sh

declare action="${0##*/}"
declare id=() name_label= name_regex= multiple=0 dry_run="${dry_run:-0}"

while getopts ":a:dhi:mn:r:" opt; do
  case $opt in
    d) dry_run=1
      ;;
    a) action="$OPTARG"
      ;;
    i) id+=( "$OPTARG" )
      ;;
    m) multiple=1
      ;;
    n) name_label="$OPTARG"
      ;;
    r) name_regex="$OPTARG"
      ;;
    h) show_help; exit 3;
      ;;
    *) die "Unrecognized/Unimplemented option '$opt'"
      ;;
  esac
done
shift "$((OPTIND - 1))"

case "$action" in
  delete) action='destroy'
    ;;
  destroy|reboot|start|stop|suspend) action="$action"
    ;;
  *) warn "Unimplemented/Unrecognized action '$action' (-a)"
     show_help; exit 3;
    ;;
esac

[[ -z ${id[@]-} && -z ${name_label-} && -z ${name_regex-} ]] &&
  die "No VM ID (-i), name label (-n), name regex (-r) specified."

if [[ -n ${id[@]-} ]]; then
  vm_def=$( vizor cloudstack vm show -i "$id" )

     id=$( jq -c -e -r '.virtualmachine[].id'    <<<"$vm_def" )
   name=$( jq -c -e -r '.virtualmachine[].name'  <<<"$vm_def" )
  state=$( jq -c -e -r '.virtualmachine[].state' <<<"$vm_def" )

  printf -v log_msg 'cloudmonkey %s virtualmachine id="%s" # %s, %56s' \
    "$action" "$id" "state=$state" "name=$name"

  if (( dry_run == 1 )); then
    echo "$log_msg"; exit 5;
  else
    log "$log_msg"
  fi

  if [[ $action = 'destroy' ]]; then
    cloudmonkey detach iso virtualmachineid="$id" &>/dev/null || true
  fi

  # TODO. Cloudmonkey emits progress info on stdout.
  ret=$( cloudmonkey "$action" virtualmachine id="$id" | sed -r '1 s/\..*\{/{/' )

  if grep -iq 'Error' <<<"$ret"; then
    die "Error actioning (action=$action) VM instance '$id' : $ret"
  else
    sed -r '1d' <<<"$ret" | jq -s -e '.'
  fi
else
  if [[ -n $name_label ]]; then
    vm_def=$(vizor cloudstack vm show -n "$name_label")
  elif [[ -n $name_regex ]]; then
    vm_def=$(vizor cloudstack vm show -r "$name_regex")
  fi

  ids=( $(jq -c -e -r '.virtualmachine[].id' <<<"$vm_def") )

  if (( ${#ids[@]} == 0 )); then
    die "No VM instances found for '$name_label'"
  elif (( ${#ids[@]} > 1 )); then
    err_msg="Multiple (${#ids[@]}) VM instances found by name '${name_label:-$name_regex}'."
    if (( multiple == 0 )); then
      die "$err_msg Will not action ('$action') multiple instances unless -m is specfied."
    else
      warn "$err_msg"
    fi
  fi

  for id in "${ids[@]}"; do
    dry_run="${dry_run}" "$0" -a "$action" -i "$id" || true
  done
fi

