#!/bin/bash

declare keyword=

if (( $# >= 1 )); then
  keyword="$@"
fi

{
  echo 'id,name,account,service offering,state,created'
  cloudmonkey list virtualmachines listall=true keyword="$keyword" |
    jq -c -r '.[][] | [.id,.name,.account,.serviceofferingname,.state,.created]' 2>/dev/null |
    sort -t , -k 6 | sed -r 's/^\[|\]$//g'
} | csv_to_table
