#!/bin/bash

declare keyword="$1"


while getopts ":k:" opt; do
  case $opt in
    k) keyword="$OPTARG"
      ;;
  esac
done

{
  echo 'id,name,hypervisor,created,isready,isfeatured,ispublic,ostypename'
  cloudmonkey list templates templatefilter=executable keyword="${keyword}" |
    jq -c -r '.[][] | [.id,.name,.hypervisor,.created,.isready,.isfeatured,.ispublic,.ostypename]' 2>/dev/null |
    sort -t , -k 4 | sed -r 's/^\[|\]$//g';
} | csv_to_table
