#!/bin/bash

source template.conf

set -eu
# set -xv

zone_id=(             $( cloudmonkey list zones name="$zone"                        | awk -F' = ' '/^id/{print $2}' ) )
echo "zone_id             : $zone_id"

iso_id=(              $( cloudmonkey list isos name="$iso"                          | awk -F' = ' '/^id/{print $2}' ) )
echo "iso_id              : $iso_id"

service_offering_id=( $( cloudmonkey list serviceofferings name="$service_offering" | awk -F' = ' '/^id/{print $2}' ) )
echo "service_offering_id : $service_offering_id"

disk_offering_id=(    $( cloudmonkey list diskofferings name="$disk_offering"       | awk -F' = ' '/^id/{print $2}' ) )
echo "disk_offering_id    : $disk_offering_id"

network_id=(          $( cloudmonkey list networks keyword="$network" listall=true  | awk -F' = ' '/^id/{print $2}' ) )
echo "network_id          : $network_id"

tmpfile="$(mktemp)"

> "$tmpfile" 2>/dev/null          \
cloudmonkey deploy virtualmachine \
  zoneid="$zone_id"               \
  templateid="$iso_id"            \
  serviceofferingid="$service_offering_id"  \
  diskofferingid="$disk_offering_id"        \
  networkids="$network_id"        \
  hypervisor="$hypervisor"        \
  displayname="$displayname"      \
  name="$name-$(date +%s)"        \
  group="$group"

cat "$tmpfile"

