#!/bin/bash

# SYNOPSIS
#   Install and configure elasticsearch

source defaults.sh
source utils.sh

distro=$(lsb_release -is | tr 'A-Z' 'a-z')
case "$distro" in
  debian|ubuntu)
    source "${DIR}/${SCRIPT##*/}.$distro"
  ;;
  centos|rhel)
    source "${DIR}/${SCRIPT##*/}.rhel"
  ;;
  *)
    die "Unsupported distribution '$distro'.";
  ;;
esac

service elasticsearch status || service elasticsearch restart | tr -d '\n'

c=0
while ! curl -s 'http://localhost:9200/'; do
  fuser -n tcp 9200 || true
  printf '.' >&2 && sleep 2
  if (( ++c == 60 )); then
    die "Timeout waiting for elasticsearch to start"
  fi
done | jq -S '.'

