#!/bin/bash

shopt -s expand_aliases extglob nullglob

DEBUG="${DEBUG}"
[[ $DEBUG ]] && set -xv

set -eu

DIR=$( cd "${BASH_SOURCE[0]%/*}" && pwd )
SCRIPT="$DIR/${BASH_SOURCE[0]##*/}"

cat "$DIR/lcids.txt"
